Baseurl          = 'https://akey.works'
Title            = 'Works.'
Publishdir       = 'docs'
Paginate         = 100

[Author]
name = 'Aki FUKAYAMA (akey)'
url  = '/about/'

[Params]
description = 'Aki FUKAYAMA (akey) is a Service Designer Based in Tokyo.'
feed        = '/feed.rss'
archives    = ['2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016']

[Taxonomies]
categories = 'categories'

[markup.goldmark.renderer]
  unsafe = true