Baseurl          = 'https://akey.works'
Title            = 'Works.'
Publishdir       = 'docs'
Paginate         = 24

[Author]
name = 'Aki FUKAYAMA (akey)'
url  = '/about/'

[Params]
description = 'Aki FUKAYAMA (akey) is a Service Designer Based in Tokyo.'
feed        = '/feed.rss'

[Taxonomies]
categories = 'categories'

[markup.goldmark.renderer]
  unsafe = true